services:
  - type: web
    name: labrecords-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MINIAPP_URL
        sync: false